// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chatSys/resign/add": {
            "post": {
                "description": "原老师绑定业务员全部转移给接替老师（去重合并），姓名/部门等冗余快照由后端回查，group_count 按原老师绑定数计算",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "离职转移"
                ],
                "summary": "新增离职转移",
                "parameters": [
                    {
                        "description": "新增离职转移请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ResignAddReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "msg 固定「转移成功」，data 恒为 null",
                        "schema": {
                            "$ref": "#/definitions/model.ActionResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法 / 原老师与接替老师相同 / transfer_content 白名单校验失败 / remark 超过 200 字符",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "老师不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/chatSys/resign/list": {
            "get": {
                "description": "分页查询离职转移记录，零值筛选字段不参与过滤；dept_id 匹配原老师部门",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "离职转移"
                ],
                "summary": "离职转移列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "原老师部门 ID",
                        "name": "dept_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "原老师 ID（精确）",
                        "name": "original_teacher_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "接替老师 ID（精确）",
                        "name": "replace_teacher_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "业务员姓名（模糊）",
                        "name": "salesman_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "转移时间起（yyyy-MM-dd，与 transfer_end_time 成对生效）",
                        "name": "transfer_begin_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "转移时间止（yyyy-MM-dd）",
                        "name": "transfer_end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码（默认 1）",
                        "name": "page_index",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小（默认 10，上限 100）",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ResignListResp"
                        }
                    },
                    "400": {
                        "description": "数字参数格式错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/chatSys/teacher/bindSales": {
            "post": {
                "description": "追加语义：仅新增绑定，已存在的绑定保持不变；重复绑定幂等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "绑定业务员"
                ],
                "summary": "绑定业务员",
                "parameters": [
                    {
                        "description": "绑定业务员请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TeacherBindReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "msg 固定「绑定成功」，data 恒为 null",
                        "schema": {
                            "$ref": "#/definitions/model.ActionResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "老师不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/chatSys/teacher/bindSales/boundUserIds": {
            "get": {
                "description": "返回全部已绑定业务员 userId（去重平铺数组），供人员树过滤已绑定人员",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "绑定业务员"
                ],
                "summary": "全量已绑定业务员",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TeacherBoundResp"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/chatSys/teacher/bindSales/list": {
            "get": {
                "description": "分页查询指定老师已绑定的业务员（手机号/昵称/部门/绑定时间）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "绑定业务员"
                ],
                "summary": "老师绑定业务员列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "老师 ID",
                        "name": "teacher_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码（默认 1）",
                        "name": "page_index",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小（默认 5，上限 100）",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TeacherSalesListResp"
                        }
                    },
                    "400": {
                        "description": "teacher_id 缺失或非法",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/chatSys/teacher/list": {
            "get": {
                "description": "分页查询老师，零值筛选字段不参与过滤；姓名/账号/昵称/头衔/操作人模糊匹配，部门/ID/认证/状态精确匹配",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "老师管理"
                ],
                "summary": "老师列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "部门 ID",
                        "name": "dept_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "老师 ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账号（模糊）",
                        "name": "account",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "昵称（模糊）",
                        "name": "nickname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "姓名（模糊）",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "头衔（模糊）",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "已认证",
                            "未认证"
                        ],
                        "type": "string",
                        "description": "认证状态（精确：已认证/未认证）",
                        "name": "qualification",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "绑定业务员数（精确；传 0 是有效过滤值）",
                        "name": "bind_sales_count",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "1",
                            "0"
                        ],
                        "type": "string",
                        "description": "状态（精确：1 启用 / 0 停用）",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "操作人（模糊）",
                        "name": "update_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "更新时间起（yyyy-MM-dd，与 update_end_time 成对生效）",
                        "name": "update_begin_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "更新时间止（yyyy-MM-dd）",
                        "name": "update_end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码（默认 1）",
                        "name": "page_index",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小（默认 10，上限 100）",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TeacherListResp"
                        }
                    },
                    "400": {
                        "description": "数字参数格式错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/chatSys/teacher/options": {
            "get": {
                "description": "全量老师选项（含停用，离职转移弹窗用）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "老师管理"
                ],
                "summary": "老师下拉选项",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TeacherOptionsResp"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/chatSys/teacher/update": {
            "put": {
                "description": "编辑头衔/评级/头像/签名（仅这 4 个字段可改，冗余快照字段一律忽略）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "老师管理"
                ],
                "summary": "编辑老师",
                "parameters": [
                    {
                        "description": "编辑老师请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TeacherUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "msg 固定「编辑成功」，data 恒为 null",
                        "schema": {
                            "$ref": "#/definitions/model.ActionResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法 / rating 非 0/1/2 / 签名超过 200 字符",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "老师不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/diagnose/audit": {
            "post": {
                "description": "professional 专业审核（状态 2）/ compliance 合规审核（状态 4）；通过 → 3/6，驳回 → 5/4（驳回时 reject_reason 必填，富文本 HTML）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "诊股记录"
                ],
                "summary": "审核诊股报告",
                "parameters": [
                    {
                        "description": "审核请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DiagnoseAuditReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "msg 为「审核通过」或「已驳回」，data 恒为 null",
                        "schema": {
                            "$ref": "#/definitions/model.ActionResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法 / audit_type 或 result 非法 / 驳回时原因必填 / 当前状态不允许审核",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "诊股记录不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/diagnose/detail": {
            "get": {
                "description": "诊股记录全字段 + 审核流程日志（audit_logs）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "诊股记录"
                ],
                "summary": "诊股记录详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "诊股记录 ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.DiagnoseDetailResp"
                        }
                    },
                    "400": {
                        "description": "id 缺失或非整数",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "诊股记录不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/diagnose/list": {
            "get": {
                "description": "分页查询诊股记录，零值/未传筛选字段不参与过滤；昵称/姓名/股票代码/股票名/老师模糊匹配，ID/买入价/持仓数/状态精确匹配",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "诊股记录"
                ],
                "summary": "诊股记录列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "诊股记录 ID（精确）",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户昵称（模糊）",
                        "name": "user_nick_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户姓名（模糊）",
                        "name": "user_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "股票代码（模糊）",
                        "name": "stock_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "股票名称（模糊）",
                        "name": "stock_name",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "买入价（精确，DECIMAL 等值匹配）",
                        "name": "buy_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "持仓数（精确）",
                        "name": "buy_num",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "老师姓名（模糊）",
                        "name": "teacher_name",
                        "in": "query"
                    },
                    {
                        "enum": [
                            1,
                            2,
                            3,
                            4,
                            5,
                            6
                        ],
                        "type": "integer",
                        "description": "状态（精确 1-6：1 待提交 2 待审核 3 已驳回 4 待合规 5 合规驳回 6 已通过）",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "提交时间起（yyyy-MM-dd，与 submit_end_time 成对生效，闭合区间）",
                        "name": "submit_begin_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "提交时间止（yyyy-MM-dd）",
                        "name": "submit_end_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "报告提交时间起（yyyy-MM-dd，与 report_end_time 成对生效）",
                        "name": "report_begin_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "报告提交时间止（yyyy-MM-dd）",
                        "name": "report_end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码（默认 1）",
                        "name": "page_index",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小（默认 10，上限 100）",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.DiagnoseListResp"
                        }
                    },
                    "400": {
                        "description": "数值参数格式错误 / status 越界（非 1-6）",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/diagnose/submitReport": {
            "post": {
                "description": "状态 1/3/5 可提交（首次编写 / 重新提审），提交后状态统一回落 2；report_content 为富文本 HTML",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "诊股记录"
                ],
                "summary": "提交诊股报告",
                "parameters": [
                    {
                        "description": "提交报告请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DiagnoseSubmitReportReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "msg 固定「提交成功」，data 恒为 null",
                        "schema": {
                            "$ref": "#/definitions/model.ActionResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法 / 报告内容为空 / 当前状态不允许提交",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "诊股记录不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ActionResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "恒为 null"
                },
                "msg": {
                    "type": "string",
                    "example": "编辑成功"
                }
            }
        },
        "model.Diagnose": {
            "type": "object",
            "properties": {
                "buy_num": {
                    "type": "integer"
                },
                "buy_price": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                },
                "report_content": {
                    "type": "string"
                },
                "report_submit_time": {
                    "description": "NULL→\"\"",
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "stock_code": {
                    "type": "string"
                },
                "stock_name": {
                    "type": "string"
                },
                "submit_time": {
                    "type": "string"
                },
                "teacher_name": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_nick_name": {
                    "type": "string"
                }
            }
        },
        "model.DiagnoseAuditLog": {
            "type": "object",
            "properties": {
                "operator": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.DiagnoseAuditReq": {
            "type": "object",
            "properties": {
                "audit_type": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reject_reason": {
                    "type": "string"
                },
                "result": {
                    "description": "pass / reject",
                    "type": "string"
                }
            }
        },
        "model.DiagnoseDetail": {
            "type": "object",
            "properties": {
                "audit_logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.DiagnoseAuditLog"
                    }
                },
                "buy_num": {
                    "type": "integer"
                },
                "buy_price": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                },
                "report_content": {
                    "type": "string"
                },
                "report_submit_time": {
                    "description": "NULL→\"\"",
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "stock_code": {
                    "type": "string"
                },
                "stock_name": {
                    "type": "string"
                },
                "submit_time": {
                    "type": "string"
                },
                "teacher_name": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_nick_name": {
                    "type": "string"
                }
            }
        },
        "model.DiagnoseDetailResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/model.DiagnoseDetail"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.DiagnoseListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "integer",
                            "example": 15
                        },
                        "list": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Diagnose"
                            }
                        }
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.DiagnoseSubmitReportReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "report_content": {
                    "description": "富文本 HTML",
                    "type": "string"
                }
            }
        },
        "model.Resign": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "group_count": {
                    "description": "原老师绑定业务员数（一业务员一群，后端计算）",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "operate_ip": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "original_teacher_dept": {
                    "type": "string"
                },
                "original_teacher_dept_id": {
                    "type": "integer"
                },
                "original_teacher_id": {
                    "type": "integer"
                },
                "original_teacher_name": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "replace_teacher_dept": {
                    "type": "string"
                },
                "replace_teacher_id": {
                    "type": "integer"
                },
                "replace_teacher_name": {
                    "type": "string"
                },
                "salesman_dept": {
                    "type": "string"
                },
                "salesman_name": {
                    "type": "string"
                },
                "transfer_content": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "transfer_time": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.ResignAddReq": {
            "type": "object",
            "properties": {
                "original_teacher_id": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                },
                "replace_teacher_id": {
                    "type": "integer"
                },
                "transfer_content": {
                    "description": "白名单 group，非空（传 friend 400）",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.ResignListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "integer",
                            "example": 7
                        },
                        "list": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Resign"
                            }
                        }
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.Teacher": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "bind_sales_count": {
                    "description": "相关子查询带出，不落列",
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "dept_id": {
                    "type": "integer"
                },
                "dept_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "qualification": {
                    "type": "string"
                },
                "rating": {
                    "description": "种子 1-5，编辑后 0/1/2",
                    "type": "integer"
                },
                "signature": {
                    "type": "string"
                },
                "status": {
                    "description": "输出 \"1\"/\"0\"",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "update_by": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "work_no": {
                    "type": "string"
                }
            }
        },
        "model.TeacherBindReq": {
            "type": "object",
            "properties": {
                "teacher_id": {
                    "type": "integer"
                },
                "user_ids": {
                    "description": "追加语义，仅新增绑定",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "model.TeacherBoundResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1
                    ]
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.TeacherListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "integer",
                            "example": 42
                        },
                        "list": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Teacher"
                            }
                        }
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.TeacherOption": {
            "type": "object",
            "properties": {
                "dept_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.TeacherOptionsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TeacherOption"
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.TeacherSalesListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "integer",
                            "example": 3
                        },
                        "list": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.TeacherSalesRow"
                            }
                        }
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.TeacherSalesRow": {
            "type": "object",
            "properties": {
                "bind_time": {
                    "type": "string"
                },
                "dept_name": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "model.TeacherUpdateReq": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "rating": {
                    "description": "0 无 / 1 初级 / 2 高级",
                    "type": "integer"
                },
                "signature": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1/dxsf",
	Schemes:          []string{"http"},
	Title:            "im系统诊股 API",
	Description:      "chatSys（老师管理/绑定业务员/离职转移）+ 诊股记录接口。\n统一响应结构 {code, msg, data}；写操作 msg 为约定中文，查询类为 \"success\"。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
