// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/user/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "新增登录账号（仅用户名+密码；密码 bcrypt 哈希落库，nickname 取 username 兜底，role 固定 admin）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "新增用户",
                "parameters": [
                    {
                        "description": "新增用户请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AdminUserAddReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "msg 固定「新增成功」，data 恒为 null",
                        "schema": {
                            "$ref": "#/definitions/model.ActionResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法 / 用户名已存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/user/delete": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除登录账号并立即踢下线（DEL Redis 白名单，该账号当前 token 立即失效）；不能删除当前登录账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "description": "删除用户请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AdminUserDeleteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "msg 固定「删除成功」，data 恒为 null",
                        "schema": {
                            "$ref": "#/definitions/model.ActionResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法 / 不能删除当前登录账号",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/user/edit": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "编辑登录账号（password 传空串表示不修改密码；改密码且目标非操作者本人时，目标账号立即被踢下线）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "编辑用户",
                "parameters": [
                    {
                        "description": "编辑用户请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AdminUserEditReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "msg 固定「编辑成功」，data 恒为 null",
                        "schema": {
                            "$ref": "#/definitions/model.ActionResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法 / 用户名已存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/user/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "分页查询登录账号（username 模糊匹配，传空串表示未填）。密码永不返回（password 列不查，json:\"-\" 双保险）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "description": "查询条件（username 模糊匹配，传空串/null 表示未填）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AdminUserListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.AdminUserListResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dxsf/teacher/bind/salesman": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "追加语义：仅新增绑定，已存在的绑定保持不变；重复绑定幂等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "绑定业务员"
                ],
                "summary": "绑定业务员",
                "parameters": [
                    {
                        "description": "绑定业务员请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TeacherBindReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "msg 固定「绑定成功」，data 恒为 null",
                        "schema": {
                            "$ref": "#/definitions/model.ActionResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "老师不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dxsf/teacher/bind/salesman/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "分页查询指定老师已绑定的业务员（id/用户名/昵称/部门/绑定时间）；data 回显 pageIndex/pageSize",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "绑定业务员"
                ],
                "summary": "老师绑定业务员列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "老师 ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码（默认 1）",
                        "name": "page_index",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小（默认 5，上限 100）",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TeacherSalesListResp"
                        }
                    },
                    "400": {
                        "description": "id 缺失或非法",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dxsf/teacher/bind/salesman/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回全部已绑定业务员 userId（去重平铺数组），供人员树过滤已绑定人员",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "绑定业务员"
                ],
                "summary": "全量已绑定业务员",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TeacherBoundResp"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dxsf/teacher/detail": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "编辑弹窗回显（昵称/头衔/评级/头像/签名；列 rating/signature 映射接口 level/sign）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "老师管理"
                ],
                "summary": "老师详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "老师 ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TeacherDetailResp"
                        }
                    },
                    "400": {
                        "description": "id 缺失或非法",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "老师不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dxsf/teacher/diagnose/audit": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "professional 专业审核（状态 2）/ compliance 合规审核（状态 4）；通过 → 3/6，驳回 → 5/4（驳回时 reject_reason 必填，富文本 HTML）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "诊股记录"
                ],
                "summary": "审核诊股报告",
                "parameters": [
                    {
                        "description": "审核请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DiagnoseAuditReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "msg 为「审核通过」或「已驳回」，data 恒为 null",
                        "schema": {
                            "$ref": "#/definitions/model.ActionResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法 / audit_type 或 result 非法 / 驳回时原因必填 / 当前状态不允许审核",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "诊股记录不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dxsf/teacher/diagnose/detail": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "诊股记录全字段 + 审核流程日志（audit_logs）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "诊股记录"
                ],
                "summary": "诊股记录详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "诊股记录 ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.DiagnoseDetailResp"
                        }
                    },
                    "400": {
                        "description": "id 缺失或非整数",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "诊股记录不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dxsf/teacher/diagnose/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "分页查询诊股记录（筛选条件走 JSON body），零值/未传筛选字段不参与过滤；昵称/姓名/股票代码/股票名/老师模糊匹配，ID/买入价/持仓数/状态精确匹配",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "诊股记录"
                ],
                "summary": "诊股记录列表",
                "parameters": [
                    {
                        "description": "查询条件（姓名/股票类模糊匹配，ID/买入价/持仓数/状态精确；数值字段必须是 JSON number，传字符串/空串一律 400，未填传 null 或缺省）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DiagnoseListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.DiagnoseListResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法 / status 越界（非 1-6）",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dxsf/teacher/diagnose/submitReport": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "状态 1/3/5 可提交（首次编写 / 重新提审），提交后状态统一回落 2；report_content 为富文本 HTML",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "诊股记录"
                ],
                "summary": "提交诊股报告",
                "parameters": [
                    {
                        "description": "提交报告请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DiagnoseSubmitReportReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "msg 固定「提交成功」，data 恒为 null",
                        "schema": {
                            "$ref": "#/definitions/model.ActionResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法 / 报告内容为空 / 当前状态不允许提交",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "诊股记录不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dxsf/teacher/edit": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "编辑头衔/评级/头像/签名（仅这 4 个字段可改，冗余快照字段一律忽略；level 0 无 / 3 初级 / 5 高级）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "老师管理"
                ],
                "summary": "编辑老师",
                "parameters": [
                    {
                        "description": "编辑老师请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TeacherUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "msg 固定「编辑成功」，data 恒为 null",
                        "schema": {
                            "$ref": "#/definitions/model.ActionResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法 / level 非 0/3/5 / 签名超过 200 字符",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "老师不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dxsf/teacher/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "分页查询老师（筛选条件走 JSON body），未传/null 字段不参与过滤；姓名/账号/昵称/头衔/操作人模糊匹配，部门/ID/认证/状态精确匹配",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "老师管理"
                ],
                "summary": "老师列表",
                "parameters": [
                    {
                        "description": "查询条件（数值字段传 null 表示未填）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TeacherListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TeacherListResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dxsf/teacher/options": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "全量老师选项（含停用，离职转移弹窗用）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "老师管理"
                ],
                "summary": "老师下拉选项",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TeacherOptionsResp"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dxsf/teacher/resign/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "原老师绑定业务员全部转移给接替老师（去重合并），姓名/部门等冗余快照由后端回查，group_count 按原老师绑定数计算；原老师无绑定业务员时 400",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "离职转移"
                ],
                "summary": "新增离职转移",
                "parameters": [
                    {
                        "description": "新增离职转移请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ResignAddReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "msg 固定「转移成功」，data 恒为 null",
                        "schema": {
                            "$ref": "#/definitions/model.ActionResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法 / 原老师与接替老师相同 / 转移内容超过 200 字符 / 原老师无绑定业务员",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "老师不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/dxsf/teacher/resign/list": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "分页查询离职转移记录（筛选条件走 JSON body，姓名类为模糊匹配，dept_id 精确匹配原老师部门快照，空值表示未填）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "离职转移"
                ],
                "summary": "离职转移列表",
                "parameters": [
                    {
                        "description": "查询条件（姓名类模糊匹配，dept_id 精确，传空串/null 表示未填）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ResignListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ResignListResp"
                        }
                    },
                    "400": {
                        "description": "请求体非法",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/getinfo": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回角色/昵称等（gyz-admin 动态路由依赖 roles 非空）。需登录态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "当前用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetInfoResp"
                        }
                    },
                    "401": {
                        "description": "登录已过期，请重新登录",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "账号密码登录，签发 Bearer token（Redis 白名单单设备模式：重新登录即互踢旧设备）。phone_code/uuid 等多余字段忽略不校验",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录凭据",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LoginResp"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除 Redis 白名单使 token 立即失效（幂等）。需登录态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "msg 为 退出成功",
                        "schema": {
                            "$ref": "#/definitions/model.ActionResp"
                        }
                    },
                    "401": {
                        "description": "登录已过期，请重新登录",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ActionResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "恒为 null"
                },
                "msg": {
                    "type": "string",
                    "example": "编辑成功"
                }
            }
        },
        "model.AdminUser": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_login_at": {
                    "type": "string"
                },
                "last_login_ip": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "description": "1 启用 / 0 停用",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.AdminUserAddReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 6,
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "tom"
                }
            }
        },
        "model.AdminUserDeleteReq": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "model.AdminUserEditReq": {
            "type": "object",
            "required": [
                "id",
                "username"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 2
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 6,
                    "example": "newpass123"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "tom"
                }
            }
        },
        "model.AdminUserListReq": {
            "type": "object",
            "properties": {
                "page_index": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 10
                },
                "username": {
                    "type": "string",
                    "example": "tom"
                }
            }
        },
        "model.AdminUserListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "integer",
                            "example": 2
                        },
                        "list": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.AdminUser"
                            }
                        }
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.Diagnose": {
            "type": "object",
            "properties": {
                "buy_num": {
                    "type": "integer"
                },
                "buy_price": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                },
                "report_content": {
                    "type": "string"
                },
                "report_submit_time": {
                    "description": "NULL→\"\"",
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "stock_code": {
                    "type": "string"
                },
                "stock_name": {
                    "type": "string"
                },
                "submit_time": {
                    "type": "string"
                },
                "teacher_name": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_nick_name": {
                    "type": "string"
                }
            }
        },
        "model.DiagnoseAuditLog": {
            "type": "object",
            "properties": {
                "operator": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.DiagnoseAuditReq": {
            "type": "object",
            "properties": {
                "audit_type": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reject_reason": {
                    "type": "string"
                },
                "result": {
                    "description": "pass / reject",
                    "type": "string"
                }
            }
        },
        "model.DiagnoseDetail": {
            "type": "object",
            "properties": {
                "audit_logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.DiagnoseAuditLog"
                    }
                },
                "buy_num": {
                    "type": "integer"
                },
                "buy_price": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                },
                "report_content": {
                    "type": "string"
                },
                "report_submit_time": {
                    "description": "NULL→\"\"",
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "stock_code": {
                    "type": "string"
                },
                "stock_name": {
                    "type": "string"
                },
                "submit_time": {
                    "type": "string"
                },
                "teacher_name": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_nick_name": {
                    "type": "string"
                }
            }
        },
        "model.DiagnoseDetailResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/model.DiagnoseDetail"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.DiagnoseListReq": {
            "type": "object",
            "properties": {
                "buy_num": {
                    "description": "精确",
                    "type": "integer"
                },
                "buy_price": {
                    "description": "精确，DECIMAL 等值匹配",
                    "type": "number"
                },
                "id": {
                    "description": "精确",
                    "type": "integer"
                },
                "page_index": {
                    "description": "默认 1（service 层兜底）",
                    "type": "integer"
                },
                "page_size": {
                    "description": "默认 10，上限 100",
                    "type": "integer"
                },
                "report_begin_time": {
                    "type": "string"
                },
                "report_end_time": {
                    "type": "string"
                },
                "status": {
                    "description": "精确 1-6",
                    "type": "integer"
                },
                "stock_code": {
                    "description": "模糊",
                    "type": "string"
                },
                "stock_name": {
                    "description": "模糊",
                    "type": "string"
                },
                "submit_begin_time": {
                    "description": "yyyy-MM-dd，与 EndTime 成对生效（闭合区间）",
                    "type": "string"
                },
                "submit_end_time": {
                    "type": "string"
                },
                "teacher_name": {
                    "description": "模糊",
                    "type": "string"
                },
                "user_name": {
                    "description": "模糊",
                    "type": "string"
                },
                "user_nick_name": {
                    "description": "模糊",
                    "type": "string"
                }
            }
        },
        "model.DiagnoseListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "integer",
                            "example": 15
                        },
                        "list": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Diagnose"
                            }
                        }
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.DiagnoseSubmitReportReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "report_content": {
                    "description": "富文本 HTML",
                    "type": "string"
                }
            }
        },
        "model.GetInfoResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/model.UserInfo"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.LoginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "admin123"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "model.LoginResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "恒为 null"
                },
                "expire": {
                    "description": "JWT exp（Unix 秒）",
                    "type": "integer",
                    "example": 1724054400
                },
                "msg": {
                    "type": "string",
                    "example": "登录成功"
                },
                "passwd_expired": {
                    "description": "密码是否过期（暂恒 false）",
                    "type": "boolean",
                    "example": false
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                }
            }
        },
        "model.Resign": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "group_count": {
                    "description": "原老师绑定业务员数（一业务员一群，后端计算）",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "operator": {
                    "type": "string"
                },
                "original_teacher_dept": {
                    "type": "string"
                },
                "original_teacher_dept_id": {
                    "type": "integer"
                },
                "original_teacher_id": {
                    "type": "integer"
                },
                "original_teacher_name": {
                    "type": "string"
                },
                "replace_teacher_dept": {
                    "type": "string"
                },
                "replace_teacher_id": {
                    "type": "integer"
                },
                "replace_teacher_name": {
                    "type": "string"
                },
                "salesman_dept": {
                    "type": "string"
                },
                "salesman_name": {
                    "type": "string"
                },
                "transfer_content": {
                    "type": "string"
                },
                "transfer_time": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.ResignAddReq": {
            "type": "object",
            "properties": {
                "original_teacher_id": {
                    "type": "integer"
                },
                "replace_teacher_id": {
                    "type": "integer"
                },
                "transfer_content": {
                    "description": "自由文本，≤200 字符",
                    "type": "string"
                }
            }
        },
        "model.ResignListReq": {
            "type": "object",
            "properties": {
                "dept_id": {
                    "description": "精确，匹配 original_teacher_dept_id 快照，''/null/缺省不过滤",
                    "type": "integer"
                },
                "original_teacher": {
                    "description": "模糊，匹配 original_teacher_name",
                    "type": "string"
                },
                "page_index": {
                    "description": "默认 1（service 层兜底）",
                    "type": "integer"
                },
                "page_size": {
                    "description": "默认 10，上限 100",
                    "type": "integer"
                },
                "replace_teacher": {
                    "description": "模糊，匹配 replace_teacher_name",
                    "type": "string"
                },
                "salesman": {
                    "description": "模糊，匹配 salesman_name",
                    "type": "string"
                },
                "transfer_begin_time": {
                    "description": "yyyy-MM-dd，与 EndTime 成对生效",
                    "type": "string"
                },
                "transfer_end_time": {
                    "type": "string"
                }
            }
        },
        "model.ResignListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "integer",
                            "example": 7
                        },
                        "list": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Resign"
                            }
                        }
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.Teacher": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "bind_sales_count": {
                    "description": "相关子查询带出，不落列",
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "dept_id": {
                    "type": "integer"
                },
                "dept_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "qualification": {
                    "type": "string"
                },
                "rating": {
                    "description": "种子 1-5，编辑后 0/1/2",
                    "type": "integer"
                },
                "signature": {
                    "type": "string"
                },
                "status": {
                    "description": "输出 \"1\"/\"0\"",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "update_by": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "work_no": {
                    "type": "string"
                }
            }
        },
        "model.TeacherBindReq": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "老师表 id（接口键名 id，内部字段语义仍为 teacher_id）",
                    "type": "integer"
                },
                "user_ids": {
                    "description": "追加语义，仅新增绑定",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "model.TeacherBoundResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1
                    ]
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.TeacherDetail": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "description": "0 无 / 3 初级 / 5 高级",
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "sign": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.TeacherDetailResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/model.TeacherDetail"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.TeacherListReq": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "模糊",
                    "type": "string"
                },
                "bind_sales_count": {
                    "description": "精确，未填不过滤；0 是有效过滤值",
                    "type": "integer"
                },
                "dept_id": {
                    "description": "精确，null/\"\"/缺省不过滤",
                    "type": "integer"
                },
                "id": {
                    "description": "精确，null/\"\"/缺省不过滤",
                    "type": "integer"
                },
                "name": {
                    "description": "模糊",
                    "type": "string"
                },
                "nickname": {
                    "description": "模糊",
                    "type": "string"
                },
                "page_index": {
                    "description": "默认 1（service 层兜底）",
                    "type": "integer"
                },
                "page_size": {
                    "description": "默认 10，上限 100",
                    "type": "integer"
                },
                "qualification": {
                    "description": "精确（中文）",
                    "type": "string"
                },
                "status": {
                    "description": "-1 全部不过滤 / 1 启用 / 0 停用",
                    "type": "integer"
                },
                "title": {
                    "description": "模糊",
                    "type": "string"
                },
                "update_begin_time": {
                    "description": "yyyy-MM-dd，与 EndTime 成对生效",
                    "type": "string"
                },
                "update_by": {
                    "description": "模糊",
                    "type": "string"
                },
                "update_end_time": {
                    "type": "string"
                }
            }
        },
        "model.TeacherListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "integer",
                            "example": 42
                        },
                        "list": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Teacher"
                            }
                        }
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.TeacherOption": {
            "type": "object",
            "properties": {
                "dept_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.TeacherOptionsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TeacherOption"
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.TeacherSalesListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "integer",
                            "example": 3
                        },
                        "list": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.TeacherSalesRow"
                            }
                        },
                        "pageIndex": {
                            "type": "integer",
                            "example": 1
                        },
                        "pageSize": {
                            "type": "integer",
                            "example": 5
                        }
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.TeacherSalesRow": {
            "type": "object",
            "properties": {
                "bind_time": {
                    "type": "string"
                },
                "dept_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.TeacherUpdateReq": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "description": "0 无 / 3 初级 / 5 高级（前端 editForm 下拉取值）",
                    "type": "integer"
                },
                "sign": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.UserInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": ""
                },
                "introduction": {
                    "type": "string",
                    "example": ""
                },
                "name": {
                    "type": "string",
                    "example": "系统管理员"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "*:*:*"
                    ]
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "admin"
                    ]
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "值格式：Bearer {token}，登录接口签发",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "im系统诊股 API",
	Description:      "chatSys（老师管理/绑定业务员/离职转移）+ 诊股记录接口。\n统一响应结构 {code, msg, data}；写操作 msg 为约定中文，查询类为 \"success\"。\n业务接口需 Bearer token（JWT + Redis 白名单，见 PLAN-auth.md）。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
